name: Tests and Build

on: [push]

jobs:
  test_and_build:
    name: Test and Build Application
    runs-on: macOS-latest
    strategy:
      matrix:
        workspace: [chronograph.xcworkspace]
        scheme: [chronograph]
        destination: [ "platform=macOS,arch=x86_64" ]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run Tests
      run: |
        xcodebuild -workspace ${{matrix.workspace}} -scheme ${{matrix.scheme}} -destination ${{matrix.destination}} clean test
    - name: Build Application
      run: |
        xcodebuild -workspace ${{matrix.workspace}} -scheme ${{matrix.scheme}} -destination ${{matrix.destination}} clean build
